### ISSUE TITLE
Plans to implement WebView2 to use Chromium based Edge?

### ISSUE THREAD

**Issue by ghost** [JBildstein/SpiderEye#14]
Just wondering if you have any plans to implement WebView2?

I understand that there is no official .NET / WinForms control for this yet, but the one that I found here looks pretty good - https://github.com/michael-russin/webview2-control

**Comment by ABildstein** [comment]
Yes, absolutely! I'm just waiting for the official .NET support to come out.

I saw that project and looked at the source a little while ago but I'd like to keep dependencies low and use official APIs if possible.

**Comment by ghost** [comment]
You could also import the code just for the WinForm control instead of using it as a dependency. It doesn't look like much. Maybe a few thousand lines of interop boilerplate. Of course that's still orders of magnitudes harder to maintain, but it is just an interop wrapper for the official C++ library.

You might also attain greater control over the component if you use their SDK via interop instead of using the eventual, official WinForms component.

I think I had read somewhere that Microsoft will be making WebView2 the default in WinForms. But, I'm wondering what their schedule is for that. They just released a WebView2 control (preview) for WinUI in February. (My bet: we won't have a WinForms control until next year especially given the current events.)

**Comment by ABildstein** [comment]
Yeah that'd be a possibility but that's still kind of a dependency with the additional drawback of not getting any updates (at least not automatically).

With the official API I'm actually using the Windows API and not the final WinForms component. I already do the same for the Edge webview. It's basically the same as the interop wrapper from your linked repo, just made by Microsoft.

It might make sense to use a subset of that interop code now to get things working and once Microsoft releases a .NET API, replace it with that. I'll look into that some more but may wait until version 1.0 of the SDK is out (it's currently still in preview, [see here](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2)) because breaking changes are still expected.

**Comment by ghost** [comment]
Sounds good. I'll leave it to you, thanks!

**Comment by ghost** [comment]
As I'm looking around today I also see this - https://github.com/webview-cs/webview-cs - which is based on https://github.com/zserge/webview which has a lot of interest and there's talk of creating an organization around it.

**Comment by bddckr** [comment]
It looks like this project is up to date with the recent big changes to zserge/webview: https://github.com/geaz/sharpWebview
